project:
  type: website
  output-dir: docs

website:
  title: "myblog"
  navbar:
    background: primary
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: sketchy
    # theme:
    #   dark: darkly
    #   light: flatly
    css: styles.css



